import Foundation
import WidgetKit

// ─── Task ──────────────────────────────────────────────────────────────────

struct WidgetTask: Codable, Identifiable, Hashable {
    let id: String
    let title: String
    let completed: Bool
    let startHour: Int?
    let startMinute: Int?
    let type: String?         // "task" | "deadline" | "break"
    let complexity: String?   // "hard" | "medium" | "easy" | nil — "hard" == a Deep Work block

    var timeLabel: String? {
        guard let h = startHour, let m = startMinute else { return nil }
        let h12  = h % 12 == 0 ? 12 : h % 12
        let ampm = h < 12 ? "AM" : "PM"
        return String(format: "%d:%02d %@", h12, m, ampm)
    }

    var minutesFromMidnight: Int? {
        guard let h = startHour else { return nil }
        return h * 60 + (startMinute ?? 0)
    }
}

// ─── AI-computed status metrics (0-100, already scored on the JS side) ─────

struct WidgetMetric: Codable {
    let value: Int?    // nil == not enough history yet ("still building")
    let label: String
}

struct WidgetMetrics: Codable {
    let recoveryIndex: WidgetMetric?
    let mentalBattery: WidgetMetric?
    let momentum: WidgetMetric?
    let deepWorkCapacity: WidgetMetric?
    let consistencyStreakDays: Int?
}

// ─── Health (only ever present when HealthKit is connected — never fabricated) ─

struct WidgetHealth: Codable {
    let sleepLastNightMinutes: Int?
    let sleepBaselineMinutes: Int?
    let recoveryScore: Int?
    let stepsToday: Int?
    let stepsBaseline: Int?
}

// ─── Morning Check-Up ────────────────────────────────────────────────────────

struct WidgetCheckup: Codable {
    let completedToday: Bool
    let readinessLabel: String?
    let readinessPct: Int?
}

// ─── Guided Journey ──────────────────────────────────────────────────────────

struct WidgetMilestone: Codable, Identifiable, Hashable {
    let id: String
    let title: String
    let done: Bool
}

struct WidgetJourney: Codable, Identifiable {
    let id: String
    let title: String
    let domain: String
    let stage: String
    let progress: Int
    let milestones: [WidgetMilestone]
    let estimatedDuration: String?

    var nextMilestone: WidgetMilestone? { milestones.first(where: { !$0.done }) }
    var milestonesDoneCount: Int { milestones.filter(\.done).count }
}

// ─── AI Insight — pre-generated by Atlas on the JS side, the widget only displays ─

struct WidgetInsight: Codable {
    let headline: String
    let detail: String?
}

// ─── Root payload written by the JS app via NoraWidgetBridgePlugin ─────────

struct WidgetData: Codable {
    var date: String
    var lastUpdated: String
    var totalToday: Int
    var completedToday: Int
    var todayTasks: [WidgetTask]
    var energy: Int
    var focus: Int
    var relaxation: Int
    var readinessLabel: String
    var readinessPct: Int
    var metrics: WidgetMetrics?
    var health: WidgetHealth?
    var checkup: WidgetCheckup?
    var journey: WidgetJourney?
    var insight: WidgetInsight?
    var weeklyCompletionPct: [Int]?

    var progress: Double {
        totalToday > 0 ? Double(completedToday) / Double(totalToday) : 0
    }

    var nextTask: WidgetTask? {
        todayTasks
            .filter { !$0.completed }
            .sorted { ($0.minutesFromMidnight ?? Int.max) < ($1.minutesFromMidnight ?? Int.max) }
            .first
    }

    var remainingDeepWorkCount: Int {
        todayTasks.filter { $0.complexity == "hard" && !$0.completed }.count
    }

    static var placeholder: WidgetData {
        WidgetData(
            date: "Monday, Jun 29",
            lastUpdated: "",
            totalToday: 5,
            completedToday: 2,
            todayTasks: [
                WidgetTask(id: "1", title: "Morning review",       completed: true,  startHour: 9,  startMinute: 0,  type: "task", complexity: nil),
                WidgetTask(id: "2", title: "Team standup",         completed: false, startHour: 10, startMinute: 30, type: "task", complexity: nil),
                WidgetTask(id: "3", title: "Deep work session",    completed: false, startHour: 14, startMinute: 0,  type: "task", complexity: "hard"),
                WidgetTask(id: "4", title: "Review pull requests", completed: false, startHour: 16, startMinute: 0,  type: "task", complexity: nil),
            ],
            energy: 7, focus: 8, relaxation: 6,
            readinessLabel: "Stable",
            readinessPct: 72,
            metrics: WidgetMetrics(
                recoveryIndex: WidgetMetric(value: 78, label: "Stable"),
                mentalBattery: WidgetMetric(value: 66, label: "Adequate"),
                momentum: WidgetMetric(value: 61, label: "Stable"),
                deepWorkCapacity: WidgetMetric(value: 70, label: "High"),
                consistencyStreakDays: 4
            ),
            health: WidgetHealth(
                sleepLastNightMinutes: 438, sleepBaselineMinutes: 452,
                recoveryScore: 74, stepsToday: 6400, stepsBaseline: 9000
            ),
            checkup: WidgetCheckup(completedToday: true, readinessLabel: "Stable", readinessPct: 72),
            journey: WidgetJourney(
                id: "j1", title: "Home Fitness", domain: "fitness", stage: "execute", progress: 42,
                milestones: [
                    WidgetMilestone(id: "m1", title: "Week 1-2: Learn the basics", done: true),
                    WidgetMilestone(id: "m2", title: "Week 3-4: Build consistency", done: false),
                ],
                estimatedDuration: "8-12 weeks"
            ),
            insight: WidgetInsight(headline: "You recovered well last night.", detail: "Today is a good day for Deep Work."),
            weeklyCompletionPct: [40, 55, 70, 60, 80, 65, 72]
        )
    }
}

// ─── Time-of-day phase — drives Part 5's "Smart Widgets" adaptive content.
// Computed from each TimelineEntry's own `date`, not stored in the payload,
// so the whole day's entries can be scheduled up front (see NoraProvider). ──

enum DayPhase: String, Codable {
    case morning, afternoon, evening

    static func forHour(_ hour: Int) -> DayPhase {
        switch hour {
        case 5..<12:  return .morning
        case 12..<18: return .afternoon
        default:      return .evening
        }
    }
}

struct NoraEntry: TimelineEntry {
    let date: Date
    let data: WidgetData
    var phase: DayPhase = .morning
    var isPlaceholder: Bool = false
}

// ─── Shared App Group storage — read by every widget kind, written by the
// main app; also supports one narrow write-back path (a pending-action
// queue) for interactive widget buttons, since the widget extension process
// is never the source of truth for the real task list. ────────────────────

enum WidgetStore {
    static let appGroupID = "group.tech.dongar.nora"
    static let dataKey = "nora_widget_data"
    static let pendingActionsKey = "nora_widget_pending_actions"

    static var defaults: UserDefaults? { UserDefaults(suiteName: appGroupID) }

    static func load() -> WidgetData {
        guard
            let defaults = defaults,
            let jsonString = defaults.string(forKey: dataKey),
            let jsonData = jsonString.data(using: .utf8),
            let data = try? JSONDecoder().decode(WidgetData.self, from: jsonData)
        else { return .placeholder }
        return data
    }

    private static func save(_ data: WidgetData) {
        guard
            let defaults = defaults,
            let jsonData = try? JSONEncoder().encode(data),
            let jsonString = String(data: jsonData, encoding: .utf8)
        else { return }
        defaults.set(jsonString, forKey: dataKey)
    }

    /// Optimistic local update so a tap reflects instantly, before the main
    /// app ever runs — the authoritative change is queued separately (see
    /// enqueuePendingAction) for the JS app's real task list to apply next
    /// time it's foregrounded, exactly like executeAiTool's complete_task.
    static func markTaskCompletedLocally(taskId: String) {
        var data = load()
        var completedDelta = 0
        data.todayTasks = data.todayTasks.map { task in
            guard task.id == taskId, !task.completed else { return task }
            completedDelta = 1
            return WidgetTask(id: task.id, title: task.title, completed: true, startHour: task.startHour, startMinute: task.startMinute, type: task.type, complexity: task.complexity)
        }
        data.completedToday += completedDelta
        save(data)
    }

    static func enqueuePendingAction(type: String, taskId: String) {
        guard let defaults = defaults else { return }
        var actions = pendingActions()
        actions.append(WidgetPendingAction(type: type, taskId: taskId, at: Date().timeIntervalSince1970))
        if let data = try? JSONEncoder().encode(actions), let str = String(data: data, encoding: .utf8) {
            defaults.set(str, forKey: pendingActionsKey)
        }
    }

    static func pendingActions() -> [WidgetPendingAction] {
        guard
            let defaults = defaults,
            let str = defaults.string(forKey: pendingActionsKey),
            let data = str.data(using: .utf8),
            let actions = try? JSONDecoder().decode([WidgetPendingAction].self, from: data)
        else { return [] }
        return actions
    }
}

struct WidgetPendingAction: Codable {
    let type: String   // "complete_task"
    let taskId: String
    let at: TimeInterval
}
